schema_version: 1

context:
  name: fvdb-core
  version: 0.3.0
  torch_proc_type: ${{ "cuda" if cuda_compiler_version != "None" else "cpu" }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fvdb_core-${{ version }}.tar.gz
  sha256: f6ec0d5e6a2b601632720ed0be8aa7c8ba6f2d9bd63fac477cef2cfd088b5f16

build:
  number: 1
  skip: cuda_compiler_version == "None" or win or osx
  script:
    env:
      TORCH_CUDA_ARCH_LIST: '7.5;8.0;9.0;10.0;12.0+PTX'

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('cuda') }}
    - if: cuda_compiler_version != "None"
      then: cuda-version ==${{ cuda_compiler_version }}
    - cuda-command-line-tools
    - cmake >=3.25
    - ninja
    - pkg-config
    - git
    - procps-ng  # provides 'free'
    - coreutils  # provides 'nproc', 'awk', etc.
  host:
    - python
    - scikit-build-core
    - pip
    - pytorch <2.10[build="*${{ torch_proc_type }}*"]
    - numpy
    - pybind11 >=2.13
    - gitpython
    - if: cuda_compiler_version != "None"
      then: cuda-version ==${{ cuda_compiler_version }}
    - cuda-cudart-dev
    - cuda-nvrtc-dev
    - cuda-nvtx-dev
    - libcublas-dev
    - libcudnn-dev
    - libcusolver-dev
    - libcusparse-dev
    - libpng
    - zlib
  run:
    - python
    - pytorch <2.10[build="*${{ torch_proc_type }}*"]
    - ${{ pin_compatible('numpy') }}
    - if: cuda_compiler_version != "None"
      then: cuda-version ==${{ cuda_compiler_version }}
    - gitpython
    - git
    - parameterized

tests:
  - files:
      source:
        - tests/
      recipe:
        - run_test.py
    requirements:
      run:
        - pip
        - pytest
        - parameterized
        - git
    script:
      - pip check
      - python run_test.py

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A deep learning framework for sparse, large-scale, high-performance spatial intelligence
  homepage: https://www.openvdb.org/
  repository: https://github.com/openvdb/fvdb-core
  documentation: https://fvdb.ai/

extra:
  recipe-maintainers:
    - jameslamb
    - swahtz
