azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 10GiB
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  linux_aarch64: linux_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
